services:
  relay:
    build:
      context: .
      dockerfile: Dockerfile
    image: anon-relay:latest
    pull_policy: build
    container_name: anon-relay
    init: true
    restart: unless-stopped
    ports:
      - "9091:9091"
    # volumes:
      # - anon_docker:/var/lib/anon/
      # - anon_docker:/etc/anon/
      # - anon_docker:/run/anon/ #Optional dir for NYX
    configs:
      - source: anonrc
        target: /etc/anon/anonrc

volumes:
  anon_docker:

configs:
  anonrc:
    content: |
      # user anond
      # DataDirectory /var/lib/anon
      # ControlPort 9051
      ControlSocket /run/anon/control
      ControlSocketsGroupWritable 1
      CookieAuthentication 1
      CookieAuthFile /run/anon/control.authcookie
      CookieAuthFileGroupReadable 1
      Log notice file /var/log/anon/notices.log
      ORPort 9091
      ExitRelay 0
      Nickname test
      ContactInfo test@test.io
      AgreeToTerms 1
