services:
  anon-relay:
    build:
      context: .
      dockerfile: Dockerfile
    image: anon-relay:latest
    pull_policy: build
    container_name: anon-relay
    init: true
    restart: unless-stopped
    ports:
      - "9091:9091"
    configs:
      - source: anonrc
        target: /etc/anon/anonrc

configs:
  anonrc:
    content: |
      ControlPort 9051
      Log notice file /var/log/anon/notices.log
      ORPort 9001
      ExitRelay 0
      Nickname MyRelayNickname
      ContactInfo my@example.mail
      AgreeToTerms 1
